config:
  Tokens:
    identifierOpeningToken: "&%!ยง(ยง?%&"
    identifierClosingToken: "&%?ยง)ยง!%&"
  Strict: true
  propertySpecific:
    Text:
      default:
        allowLongerThanMaxDbLen: false  # Will throw an error if the default value is longer than maximum length of varchar when set to false and Strict is true