name: menucardvendor/menucardpackage
label: 'Standard extension for the menucard website'
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - typo3/felogin
  - typo3/seo-sitemap
  - typo3/indexed-search
  - typo3/form