base: typo3demo.deimos-crm.de
baseVariants:
  -
    base: 'https://menucard.ddev.site/'
    condition: 'applicationContext == "Development"'
dependencies:
  - menucardvendor/menucardpackage
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=20'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: Menucard
rootPageId: 5
websiteTitle: Menucard
